name: Setup Environment
description: Sets up Node.js/pnpm and installs the dependencies of the repo

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 22
    - run: pnpm install
      shell: bash
