[build.environment]
  NPM_FLAGS = "--version"
[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && RELEASE=true npx pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
