version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.16.0-browsers

commands:
  init_repo:
    steps:
      - checkout
      - attach_workspace:
          at: .

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - yarn-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install Packages
          command: yarn --frozen-lockfile

workflows:
  version: 2
  dev:
    jobs:
      - build

      - test:
          requires:
            - build

  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d\.\d\.\d$/

      - test:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d\.\d\.\d$/

      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d\.\d\.\d$/

jobs:
  build:
    executor: node

    steps:
      - init_repo

      - save_cache:
          paths:
            - node_modules
          key: yarn-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Build
          command: yarn build:prod

      - persist_to_workspace:
          root: .
          paths:
            - dist

  test:
    executor: node

    steps:
      - init_repo

      - run:
          name: ESLint
          command: yarn test:eslint

      - run:
          name: E2E Tests
          command: yarn test:ci

  deploy:
    executor: node

    steps:
      - init_repo

      - run:
          name: Install Netlify-CLI
          command: sudo yarn global add netlify-cli

      - run:
          name: Deploy to Netlify
          command: netlify deploy --prod
