name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn Install
        run: yarn --frozen-lockfile

      - name: Clean
        run: yarn clean

      - name: Build
        run: yarn build:prod
        env:
          RELEASE: true

      - name: Install netlify-cli
        run: sudo yarn global add netlify-cli

      - name: Deploy
        run: netlify deploy --dir dist --prod --message "Deployment of $GITHUB_REF"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
