name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Environment
        uses: ./.github/actions/setup

      - name: ESLint
        run: pnpm test:eslint

  typecheck:
    name: Type Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Environment
        uses: ./.github/actions/setup

      - name: Typecheck
        run: pnpm test:typecheck
