name: Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: ESLint
        run: yarn test:eslint

      - name: E2E Tests
        run: yarn ci
